services:
  postgres:
    image: postgres:latest
    container_name: booky-postgres
    environment:
      POSTGRES_DB: learning-spring-db
      POSTGRES_USER: booky
      POSTGRES_PASSWORD: booky
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U booky -d learning-spring-db"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  postgres_data: